-nbad
-bap
-brs
-nbc
-br
-ncdb
-cdw
-ce
-ci4
-cli4
-cs
-di2
-dj
-fc1
-i4
-l100
-lp
-nbbo
-npcs
-nprs
-npsl
-sc
-sob
-TBlock -TBlockHeap -Tdbuf -Tdbufbuf -TaConfList -TaConfEntry
-Tfdstruct -Thashentry -Treslist -Tcache -Tcachetable -TaConfItem
-TaClient -TaChannel -TanUser -TaServer -TLink -TMode -Tts_val
-TaMotd -TWhowas -Tmsg_tree -TBan -Tu_char -Tu_short -Tu_long
-Tu_int -Taname -THEADER -Tip_entry -Tgline_pending -Tscache_entry
-TNumeric -TaNUH -TMessage -TToken -Tbuf_line_t -Tbuf_head_t
